### ISSUE TITLE
Official Web-site crashed

### ISSUE THREAD

**Issue by TechQuery** [ganelson/inform-website#2]
@ganelson https://inform7.com/ is `404`...

![Screenshot_2023-12-26-11-34-07-575_com.android.chrome-edit.jpg](https://github.com/ganelson/inform-website/assets/19969570/d6c0dd56-c134-405e-8cbd-b4e721206a05)

**Comment by ganelson** [comment]
I think this was a certificate problem, and has now been fixed.
